version: "3.7"

services:
  database:
    build: ./database/mssql-docker
    container_name: database
    environment:
      - SA_PASSWORD=Haslo123!
      - ACCEPT_EULA=Y
      - TZ=Poland
    ports:
      - "1433:1433"
    networks: 
      - shared-network

  server:
    build: ./
    ports:
      - "3001:3001"
    networks: 
      - shared-network
    working_dir: /server
    command: npm start
    expose:
      - 3001
    links:
      - database
    depends_on:
      - database
    environment:
      - TZ=Poland
    restart: on-failure
    

volumes:
  global-volume:

networks:
  shared-network: {}