version: "3.7"

services:
  csr-database:
    build: ./backend/database/mssql-docker
    container_name: csr-database
    environment:
      - SA_PASSWORD=Haslo123!
      - ACCEPT_EULA=Y
      - TZ=Poland
    ports:
      - "1433:1433"
    networks: 
      - shared-network

  csr-backend:
    build: ./backend
    container_name: csr-backend
    ports:
      - "3001:3001"
    networks: 
      - shared-network
    working_dir: /backend
    command: npm start
    expose:
      - 3001
    links:
      - csr-database
    depends_on:
      - csr-database
    environment:
      - TZ=Poland
    restart: on-failure


  csr-frontend:
    build: ./frontend/auctionapp-front
    container_name: csr-frontend
    ports:
      - "3000:3000"
    networks: 
      - shared-network
    working_dir: /frontend
    command: serve -s build
    expose:
      - 3000
    links:
      - csr-backend
    depends_on:
      - csr-backend
    environment:
      - TZ=Poland
    restart: on-failure
    

volumes:
  global-volume:

networks:
  shared-network: {}